name: "forge test"
on: [push, pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dev dependencies
        run: npm install

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Set up rust cache
        uses: Swatinem/rust-cache@v1

      - name: Save git SHA for Foundry
        run: |
          echo "forge-sha=$(git ls-remote  https://github.com/gakonst/foundry HEAD | awk '{ print $1}')" >> $GITHUB_ENV

      - name: Cache Forge
        uses: actions/cache@v2
        id: cache-forge
        env:
          cache-name: cache-forge
        with:
          path: ~/.cargo/bin/forge
          key: ${{ env.cache-name }}-${{ env.forge-sha }}

      # Install on cache miss
      - name: Install Forge
        if: steps.cache-forge.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/gakonst/foundry --bin forge --locked

      - name: Source config
        run: source .dapprc

      - name: Run tests
        run: forge test
        env:
          # Only fuzz deeply if we're pushing to main or this is a PR to main:
          #TODO this is always false, need to ensure it works on CI
          DEEP_FUZZ: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}